auto: true
server: true
pygments: true
permalink: none
baseurl: ""
oauth_client_id: 3bc5cdc32addd0fbff25
gatekeeper_url: http://gatekeeper-kizu.herokuapp.com
exclude:
- .gitignore
- README.md
- node_modules
- package.json
- Gruntfile.coffee
rootUrl: kizu/kizu.github.com/tree/master/_posts
