auto: true
server: true
pygments: true
permalink: none
baseurl: ""
share_url: http://localhost:8000/channel
share: true
oauth_client_id: 8c0597999e07af860296
gatekeeper_url: http://gatekeeper.benbalter.com
exclude:
- .gitignore
- README.md
<<<<<<< HEAD
rootUrl: benbalter/benbalter.github.com/tree/master/_posts
=======
- node_modules
- package.json
- Gruntfile.coffee
rootUrl: benbalter/benbalter.github.com/tree/master/_posts
>>>>>>> gh-pages
